var car = "sabaru";
console.log(" is car == 'sabaru'? | predict true. ");
console.log(car == 'sabaru');
var name1 = "Shoaib";
console.log(name1 == "Shoaib");
var plain = "PIA";
console.log(plain == "Emirates");
var game = "Hockey";
console.log(game == "Football");
var dress = "Shirt";
console.log(dress == "shirt");
var school = "Vision";
console.log(school == "Indus");
var train = " Shalimar";
console.log(train == "GreenLine");
var train1 = "Shalimar";
console.log(train1 == "Shalimar");
var plain1 = "PIA";
console.log(plain1 === "PIA");
var game1 = "Hockey";
console.log(game1 == "Hockey");
