// // let vale1  = 25;
// let value2 = 8;
// console.log(" The SUM OF 25 AND 8 is", vale1+value2);
// console.log(" The Substraction OF 25 AND 8 is", vale1-value2);
// console.log(" The Multiplication OF 25 AND 8 is", vale1*value2);
// console.log(" The Division OF 25 AND 8 is", vale1/value2);
// let fname = "Shoaib";
// let lname = "Salman";
// let Name = (fname +' '+ lname );
// console.log(Name);
// let fname = "Shoaib";
// let lname = "Salman";
// let Name = ` ${fname} ${lname}`;
// console.log(Name);
var apples = 500;
var bags = 10;
var index = apples % bags;
console.log(index);
